### ISSUE TITLE
After flashed the firmware, the TX Module automatically enters the WIFI state

### ISSUE THREAD

**Issue by YI-BOYANG** [ExpressLRS/ExpressLRS#1482] opened 2022-03-12 07:36 UTC
I have a DIY 915 TX Module, and after brushing DIY 900 TX ESP32 SX127x E19 2.3.0 firmware, it will inevitably enter WIFI state after rebooting, and Lua cannot be used normally! Repeated repeated brushing firmware can not be solved!

**Comment by YI-BOYANG** [comment] 2022-03-24 05:58
> 

I can assure you that it was not a firmware burn error, and now I have found the cause: it was my computer! The same firmware target, burned with my friend's computer-generated firmware, returned to normal. But even if MY computer-generated firmware succeeded, the firmware wouldn't make it work, either 2.x or 1.x.

**Comment by pkendall64** [comment] 2022-03-24 06:22
So have you tried clearing the platformio cache and firmware files and rebuilding?

**Comment by YI-BOYANG** [comment] 2022-03-24 06:25
> 清除 platformio 缓存和固件文件

No, I will clear the platformio cache and firmware file first, then try to rebuild the firmware, thank you!

**Comment by pkendall64** [comment] 2022-03-25 21:56
> > 清除 platformio 缓存和固件文件
> 
> No, I will clear the platformio cache and firmware file first, then try to rebuild the firmware, thank you!

How did you get on? Can we close this issue as it's not a bug in the firmware?

**Closed** 2022-04-07 05:49 UTC
