### ISSUE TITLE
Happymodel ep2 rx flash 2.5 problem - slow blinking led - no wifi mode

### ISSUE THREAD

**Issue by SUPERBAFFOFPV** [ExpressLRS/ExpressLRS#1568] opened 2022-05-12 14:34 UTC
Hi all. I have a problem to my receiver, I just updated my new Happymodel ExpressLRS 2.4Ghz pro TX to the newest 2.5 elrs version that went fine. But once I updated my first happymodel EP2 (which was already binded to an other old tx in version 1) to the new 2.5 version, it didn't bind and now just flashes slowly, it don't even go into WiFi mode after 2 minutes passes, and even if I turn on and off the power quickly for 3 times...

The drone of the rx is the emax tinyhawk 2 freestyle and to power on the rx i need to place the battery.

The only thing that maybe I noticed is that when i built the firmware for the tx in the configurator (the last v 1.4.1), the auto wifi interval was automatically set to 60 and i left that value, but when I built the rx firmware I set it to 20... maybe that was the problem? 

Now the only option I think to have is to try flashing it via Betaflight passthrough, but i have a lot of doubts. Do I have to solder the bridge on my rx? or it is now flashed in v2 so it doesn't need that bridge? Is that the only option for me to try to solve the problem?

Thanks in advance!

**Comment by commanderguy3001** [comment] 2022-05-12 18:56
in general: if your modules (reveiver and transmitter) run different major versions (1.x vs 2.x) they won't be able to bind, you always have to have them on the same major versions (both on 1.x or both on 2.x).

Also I would recommend you check out https://expresslrs.org/2.0/quick-start/unbricking 
as it sounds to me like it might be a bad flash (did you upgrade via wifi?)

Also: the different wifi startup intervals don't make a problem, as they are only responsible for enabling wifi after that time on the specific module, which has nothing to do with inter-module communication.

**Comment by expenaticx** [comment] 2022-06-08 14:35
Hello, i have the same problem exactly as you. I had my Happymodel EP1 on version 1.2.1 working and I updated to 2.5.0 via wifi successfully (waited until it reboot and blink slowly) now it blink slowly and no wifi What can i do ?!!

**Comment by commanderguy3001** [comment] 2022-06-08 14:46
> Hello, i have the same problem exactly as you. I had my Happymodel EP1 on version 1.2.1 working and I updated to 2.5.0 via wifi successfully (waited until it reboot and blink slowly) now it blink slowly and no wifi What can i do ?!!

hi, first of all: welcome to github, in general it is the best thing to just always open a new issue if you encounter one, as that does not notify unneeded users, and especially replying to old issues like this (about a month old already) is not that good of an idea.
But, I do appreciate your effort of looking through the github issues at all, most users don't...

Now to your issue: the [LED status documentation](https://expresslrs.org/2.0/quick-start/led-status/) shows all the LED statuses that are there. a slowly blinking light generally means that the receiver is not receiving any data from your transmitter.

If I would have to take a guess on why that is: you probably forgot to update your transmitter to version 2.5, but rather left it on 1.2, which will prevent the two from connecting.

Solution to your problem: update your transmitter to version 2.5 as well.

If you want faster and easier help from even more people then I'd recommend you to hop on the [discord](https://discord.gg/expresslrs), or if you just want to hang out with others of the community!

**Comment by expenaticx** [comment] 2022-06-08 14:55
Thanks for your reply , I already updated my TX to the same version of ELRS 2.5.0 and with the same binding phrase and i can open it via Lua v2 , the problem is in the receiver that does not connect or even enter wifi mode.

**Comment by expenaticx** [comment] 2022-06-08 15:34
I am on Ardupilot right now , this mean i need install betaflight :(

**Comment by commanderguy3001** [comment] 2022-06-08 15:59
uhm no you don't _need_  to install betaflight, I think ardupilot also has a serial passthrough feature which should work just fine.
just that you probably need to start the passthrough manually (you will have to look up how to do that by yourself), and then you can use the UART flashing method in the configurator instead of betaflight passthrough.

**Comment by hdcrb** [comment] 2022-06-09 05:42
I had the exact same thing when flashing my EP1 to 2.5 via Wifi. Slow blinking LED, now Wifi.
I flashed via Wifi.

It recovered all right via Bootloader and Betaflight passthrough and now runs as if nothing ever happened.

**Comment by expenaticx** [comment] 2022-06-09 05:53
I also managed to recover my EP1 via Betaflight passthrough and runs okay on 2.5 , but i cannot enable wifi on rx via lua or by waiting (20-60 sec which it is enabled from the ELRS configurator)

**Comment by pkendall64** [comment] 2022-06-10 22:12
I'm marking this issue as "closing" as these questions should really be asked on discord in the #help-and-support channel.
Asking on discord will give you a much faster turn-around on getting your problem solved.

**Closed** 2022-06-23 03:19 UTC
Labels: closing
