### ISSUE TITLE
Model Match

### ISSUE THREAD

**Issue by harry1453** [ExpressLRS/ExpressLRS#629] opened 2021-05-20 12:51 UTC
Most protocols, including CRSF, have a receiver number that can be used to effectively assign different bound receivers to different OpenTX model configurations. Does ELRS support this? I can't find any mention of receiver number in the codebase. If not, this would be a great feature!

**Comment by jbman** [comment] 2021-05-20 17:29
This request seems to be a duplicate of issue https://github.com/ExpressLRS/ExpressLRS/issues/544

**Comment by pitts-mo** [comment] 2021-05-22 13:06
Hello @harry1453 
Are you able to add any specific concerns under #544 and close this issue?
Thank you,
-p

**Comment by harry1453** [comment] 2021-05-22 15:08
Oopsie! Didn't see that, sorry. Duplicate of #544

**Closed** 2021-05-22 15:08 UTC
Labels: enhancement
