### ISSUE TITLE
v3Lua script hangs with ELSR v3.3.0 on Taranis X9D+ with Happymodel ES24 TX v1.0

### ISSUE THREAD

**Issue by jrwrodgers** [ExpressLRS/ExpressLRS#2355] opened 2023-08-12 18:08 UTC
## Current Behavior
elrsv3.lua script hangs 
Just updated to 3.3.0 and issue started - if I revert to 3.0.0 then all works fine
## Steps to Reproduce
Load the script page from Taranis menu/tools

## Your Environment

- TX hardware: ES24 Happymodel V1.0
- RX hardware: 
- Handset model: Taranis X9D+ with EDGETX v2.8.5
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH): 3.3.0
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by pkendall64** [comment] 2023-08-12 20:59
We have a fix for this in 3.x.x-maintenance branch. The problem is that external modules no longer support 500Hz mode dues to timing issues. This was found after the release of 3.3.0.

**Closed by pkendall64** 2023-08-12 20:59 UTC
