### ISSUE TITLE
No version 3.3.0  for the SIYI FM30 at the moment

### ISSUE THREAD

**Issue by aMax52** [ExpressLRS/ExpressLRS#2328] opened 2023-07-26 12:21 UTC
## Current Behavior 
Since Configurator 1.6 has no longer DFU mode , I must use V 1.5.10

 After flashing V3.3.0, the unit does not reboot. It stays into boot mode and no led is on.
Did this two times , code was uploaded to 100%.
The only way to recover, was to build ELRS version 3.2.1  and flash. After this, the unit comes back to life again and works as normal.

## Steps to Reproduce
Nothing special.

1.

2.

3.

4.

## Your Environment

- TX hardware:
- RX hardware:
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by pkendall64** [comment] 2023-07-26 18:15
Closing as this is a duplicate of #2194 
You can always use either vscode or 1.5.10 version of configurator to flash 3.3.0 to Siyi.

**Closed by pkendall64** 2023-07-26 18:15 UTC
