### ISSUE TITLE
BETAFPV SuperD ELRS 2.4G RX wrong diversity behavior

### ISSUE THREAD

**Issue by StiOII** [ExpressLRS/ExpressLRS#2139] opened 2023-03-25 11:07 UTC
## Current Behavior

I bought two SuperD ELRS 2.4G receivers, and both of them demonstrate the same issue. One of the antenna's RSSI is never changing, active antenna number is never changing, even when I hold antennas in hand.

It looks like this receiver doesn't work as diversity but as a single channel receiver. This is not an expected behavior, and since both of them have the same issue, I believe, it's not a HW problem.

## Steps to Reproduce

Just normal use

## Your Environment

- TX hardware: Happymodel ES24TX Slim Pro 2.4G
- RX hardware: BETAFPV SuperD ELRS 2.4G
- Handset model: Taranis x9 lite
- OpenTX version: 2.3.15
- ExpressLRS version (TX & RX MUST MATCH): 3.2.0 (latest script too)
- Packet Rate: different
- Telemetry Ratio: ???
- user_defines: see screens

--

https://youtu.be/5R9MbetvL8U

![Screenshot_3](https://user-images.githubusercontent.com/126816986/227712971-333bacf8-0a08-48d3-a5c8-7f59ba605e05.png)
![Screenshot_4](https://user-images.githubusercontent.com/126816986/227712973-ce5b497c-7cab-4d04-adb3-21c2cb9dc865.png)

**Comment by pkendall64** [comment] 2023-03-25 19:34
It's not a bug, it's just a behaviour of the current implementation. This is also related to #2109.
Both radios receive the packet and the firmware reads the first one sets the RX_DONE flag, if they both do it then it will generally favour one side. We only read the second side if the first side fails it's CRC check, and we only read the RSSI/SNR from the side that passes its check.
There is a branch that is being worked on to "fix" this behaviour, but it is in the testing phase and not ready for general consumption. If you would like to test it, the branch is `true_diversity_rssi_update`.

**Comment by StiOII** [comment] 2023-03-25 20:39
Thank you very much Paul, for the explanation!

I also have Matek diversity RX and as far as I remember, it has a different behavior. That's why I was confused.
Anyway it would be nice to see both RSSIs of course.

I will try the branch you've mentioned.

Can be closed.

**Comment by pkendall64** [comment] 2023-03-25 21:07
Yes, the antenna diversity has a different behaviour, and that's what we are trying to emulate with the branch, so it looks consistent for users.

We will leave the ticket open until a pull-request is made from the branch and merged, as it helps with tracking.

**Comment by Garwol4130** [comment] 2023-04-01 08:04
> It's not a bug, it's just a behaviour of the current implementation. This is also related to #2109. Both radios receive the packet and the firmware reads the first one sets the RX_DONE flag, if they both do it then it will generally favour one side. We only read the second side if the first side fails it's CRC check, and we only read the RSSI/SNR from the side that passes its check. There is a branch that is being worked on to "fix" this behaviour, but it is in the testing phase and not ready for general consumption. If you would like to test it, the branch is `true_diversity_rssi_update`.

"fix" ? not a bug? In my case receiver (tested on both  SuperD and EP1 dual)for some reason decides that active radio is always the second one, and rssi that is updating is 2RSS and I can't put that in osd so I don't know my RSSI value when flying.. this is clearly a bug...

**Comment by pkendall64** [comment] 2023-04-01 21:35
> > It's not a bug, it's just a behaviour of the current implementation. This is also related to #2109. Both radios receive the packet and the firmware reads the first one sets the RX_DONE flag, if they both do it then it will generally favour one side. We only read the second side if the first side fails it's CRC check, and we only read the RSSI/SNR from the side that passes its check. There is a branch that is being worked on to "fix" this behaviour, but it is in the testing phase and not ready for general consumption. If you would like to test it, the branch is `true_diversity_rssi_update`.
> 
> "fix" ? not a bug? In my case receiver (tested on both SuperD and EP1 dual)for some reason decides that active radio is always the second one, and rssi that is updating is 2RSS and I can't put that in osd so I don't know my RSSI value when flying.. this is clearly a bug...

Even if we make adjustments to the way we collect RSSI for both radios, you will continue to have the issue in your OSD as you can only display 1RSS as you say. So I guess you'd call that a bug in your FC firmware.

**Comment by StiOII** [comment] 2023-04-08 21:46
I've tried true_diversity_rssi_update - looks very nice! At lease I can see in logs what happens with both antennas in flight.

**Closed** 2023-04-19 21:33 UTC
