### ISSUE TITLE
EP2 yellow light most of the time, can't connect or flash (works on another AIO)

### ISSUE THREAD

**Issue by lodriguez** [ExpressLRS/ExpressLRS#655] opened 2021-05-27 16:53 UTC
## Current Behavior

When powering on the AIO (GEP-12A-F4) I only get a solid yellow light on the EP2. I can't interact with the EP2 (no connection or Wi-Fi). After many power cycles it sometimes gets back to normal behavior… (works with another AIO [Crazybee F4 Pro])

## Steps to Reproduce

1. It's wired up like crossfire nano in this pdf
https://geprc.com/download/en/GEP-12A-F4-Manual-EN-v1_3.pdf

2. Power up the AIO

## Details
- I only have xm+, what works, but this could be still be a problem with the uart/AIO.
- like 1% of the times it just works like intended, It powers up with the blinking light, connects to the radio or goes in Wi-Fi mode after 20s
- On a Crazybee F4 Pro, the EP2 just works all the time.
- I had this problem right from the start, I flashed rc7, same.
- Flashed a new clean betaflight to the AIO, same.
- Switched between 2 EP2 multiple times, always the same result. 
- When I disconnect TX on the EP2 it starts normally. I can bind it with the radio or wait until it goes in Wi-Fi mode.
-  serialrx_inverted = OFF, serialrx_halfduplex = OFF

## Your Environment

- TX hardware: ES24TX
- RX hardware: EP2
- Handset model: Jumper T-lite
- OpenTX version (including nightly number): 2.3.12N502
- ExpressLRS version (TX & RX MUST MATCH): rc7
- Packet Rate: 250Hz
- Telemetry Ratio: 1:16
- user_defines:

**Comment by pkendall64** [comment] 2021-05-27 19:41
This is not a bug in the firmware.

This problem is well known that some FCs cause the receiver TX line to go low at power on which forces the ESP into bootloader mode, hence the solid LED.

There are a couple of potential fixes/workarounds.
- Try another UART this behaviour seems to be present on some UARTs on some FCs
- You can try is to add a small value (300ohm-1kohm) pull up resistor (to 3.3V) to the receiver TX line.

**Comment by jklong03** [comment] 2021-06-02 06:19
My research into this for my case (older Betafpv F3 brushed fc) seems to point to the issue of UARTs that are primarily serving as ADC I/O (designated tta I/O). These are 3.3v logic ports whereas UARTs that are 5v (designated FT type I/O) tolerant do not have a problem with the HM designs.

**Comment by palia95** [comment] 2021-06-15 08:06
Hi, I'm having the same issue on a Gep-20a-f4 board, is there any solution? I don't have spare UART ports. Will a PP RX work? I heard this is a EP related issue

**Comment by pkendall64** [comment] 2021-06-15 08:13
Yes, this is only a problem with the espressif based RXes

**Comment by taylormadearmy** [comment] 2021-06-15 14:51
> Hi, I'm having the same issue on a Gep-20a-f4 board, is there any solution? I don't have spare UART ports. Will a PP RX work? I heard this is a EP related issue

I have this issue on my Flight Succex-D AIO f4 FC. Beware - while the PP does work on this board - I am unable to flash it on this board, while flashing it on another board works. Not sure you will run into the same issue but thought I would let you know just in case.

**Comment by palia95** [comment] 2021-06-15 15:36
> > Hi, I'm having the same issue on a Gep-20a-f4 board, is there any solution? I don't have spare UART ports. Will a PP RX work? I heard this is a EP related issue
> 
> I have this issue on my Flight Succex-D AIO f4 FC. Beware - while the PP does work on this board - I am unable to flash it on this board, while flashing it on another board works. Not sure you will run into the same issue but thought I would let you know just in case.

Ok, thanks. I should receive my PP next week, then I'll give a try and I'll let you know

**Comment by richardbulger** [comment] 2021-06-17 12:10
Also had this behavior with my Mamba f405 stack when replacing the XM+, which was using RX1, to the EP1 on RX1 and TX1. When I moved it to RX/TX 6, it worked fine

**Comment by sweebee** [comment] 2021-06-17 13:47
@richardbulger if i'm right uart 1 on the mamba f405 has an inverted uart so it doesn't work, it needs uninverted uarts (same for crossfire).

**Comment by taylormadearmy** [comment] 2021-06-18 13:08
The issue for me is fixed on my iFlight Succex-D AIO f4 FC if I connect a 1kOhm resistor between rx and 5v on the EP1. I don't know if this is electrically bad for the EP1 in other ways.

**Comment by ballistRC** [comment] 2021-06-24 11:33
pull up to 3v3, it's safer.  I'm not sure how tolerant the ESPs are but I have blown a few uart RX.  the RX inputs on an STM32 normally should be idle high, if in fact it is idle low, then it sounds like there is additional HW between the uart pin, perhaps sbus input which will idle low.  A uart idling low would never see the start bit.

**Comment by taylormadearmy** [comment] 2021-06-24 11:41
Yeah - my eyesight is not good enough to find a 3v3 pad on the EP1 sadly...

**Comment by jms81** [comment] 2021-06-28 09:27
Hi, I had the same issue with my new Nazgul5 v2 4S. The FC is a iFlight SucceX-E F4.

I didn't wan't to solder on the FC and better use the connector.

The solution, as proposed here, was to pull up to 3v3 by adding a 1kOhm resistor between the RX pin (fc side) and a 3v3 pin. Fortunately, the connector comes with a 3v3 pin.

![image](https://user-images.githubusercontent.com/454345/123613435-b4844180-d803-11eb-9607-d6c1075bc8d9.png)

**Comment by m4journey** [comment] 2021-07-05 18:32
> 1kOhm resistor

will a 2.2ohm work as well? That's all i have with me otherwise i'll need to go buy 1kohm

**Comment by taylormadearmy** [comment] 2021-07-05 18:35
I don't think there is any harm in trying. 
If it doesn't work you could try two in series.

**Comment by m4journey** [comment] 2021-07-05 18:36
2.2k ohm

**Comment by m4journey** [comment] 2021-07-05 18:39
> I don't think there is any harm in trying.
> If it doesn't work you could try two in series.
> 
> Edit. Actually is that ohms rather than kohm? If so no, that won't work!

both my 5v pads at the moment is 1.5v on the succex f4 mini. 
If i use external 5v the radio and ep1 has solid bind. 
I'm wondering if crossfire works on this FC, why elrs has issues?!

**Comment by taylormadearmy** [comment] 2021-07-05 18:42
> 2.2k ohm

Give it a go then.

**Comment by m4journey** [comment] 2021-07-05 18:43
> ## Current Behavior
> When powering on the AIO (GEP-12A-F4) I only get a solid yellow light on the EP2. I can't interact with the EP2 (no connection or Wi-Fi). After many power cycles it sometimes gets back to normal behavior… (works with another AIO [Crazybee F4 Pro])
> 
> ## Steps to Reproduce
> 1. It's wired up like crossfire nano in this pdf
>    https://geprc.com/download/en/GEP-12A-F4-Manual-EN-v1_3.pdf
> 2. Power up the AIO
> 
> ## Details
> * I only have xm+, what works, but this could be still be a problem with the uart/AIO.
> * like 1% of the times it just works like intended, It powers up with the blinking light, connects to the radio or goes in Wi-Fi mode after 20s
> * On a Crazybee F4 Pro, the EP2 just works all the time.
> * I had this problem right from the start, I flashed rc7, same.
> * Flashed a new clean betaflight to the AIO, same.
> * Switched between 2 EP2 multiple times, always the same result.
> * When I disconnect TX on the EP2 it starts normally. I can bind it with the radio or wait until it goes in Wi-Fi mode.
> * serialrx_inverted = OFF, serialrx_halfduplex = OFF
> 
> ## Your Environment
> * TX hardware: ES24TX
> * RX hardware: EP2
> * Handset model: Jumper T-lite
> * OpenTX version (including nightly number): 2.3.12N502
> * ExpressLRS version (TX & RX MUST MATCH): rc7
> * Packet Rate: 250Hz
> * Telemetry Ratio: 1:16
> * user_defines:

Did you managed to solve your issue?
I'm having the same issue on my succex f4 min - chimeraLR4 quad.
When ep1 using ext power 5v, it binds no problem.

**Comment by m4journey** [comment] 2021-07-05 18:44
> > 2.2k ohm
> 
> Give it a go then. And if you have a 3v3 pad pull up to that instead.

Do you mean just join a 3v3 to the 5v pad? without resistor?

**Comment by taylormadearmy** [comment] 2021-07-05 18:46
No! Rx on the EP1 to a 3v3 on the FC using your 2k2 resistor

**Comment by m4journey** [comment] 2021-07-05 18:50
> No! Pull up the Rx on the EP1 to a 3v3 on the FC using your 2k2 resistor

Looking at above reply by jms81 he put ohm on 3v3 and TX(ep1) - R2.
and you said RX on ep1 which means rx to T2.

So i'm confused is it TX or RX side of the ep1?

**Comment by taylormadearmy** [comment] 2021-07-05 18:51
For me it worked on Rx on EP1. Try both and see if one works for you.

**Comment by m4journey** [comment] 2021-07-05 19:00
> For me it worked on Rx on EP1. Try both and see if one works for you.

OK i'll try, many thanks

**Comment by lodriguez** [comment] 2021-07-05 19:04
> Did you managed to solve your issue?
> I'm having the same issue on my succex f4 min - chimeraLR4 quad.
> When ep1 using ext power 5v, it binds no problem.

Nope, resistors didn't work for me, I ordered a happymodel pp rx.

**Comment by m4journey** [comment] 2021-07-05 20:43
> > Did you managed to solve your issue?
> > I'm having the same issue on my succex f4 min - chimeraLR4 quad.
> > When ep1 using ext power 5v, it binds no problem.
> 
> Nope, resistors didn't work for me, I ordered a happymodel pp rx.

I think we can try ext 5v bec. I'll try resistor mod tomorrow first. I do have a small 5v bec to try after. Will report back here.
Someone said the RC9 fixed this issue but in the description, they never mention this fix. I might just give the rc9 a try first.

**Comment by m4journey** [comment] 2021-07-05 20:59
> This is not a bug in the firmware.
> 
> This problem is well known that some FCs cause the receiver TX line to go low at power on which forces the ESP into bootloader mode, hence the solid LED.
> 
> There are a couple of potential fixes/workarounds.
> 
> * Try another UART this behaviour seems to be present on some UARTs on some FCs
> * You can try is to add a small value (300ohm-1kohm) pull up resistor (to 3.3V) to the receiver TX line.

What is ESP? You refer to Receiver or Flight controller side?

**Comment by pkendall64** [comment] 2021-07-05 21:09
The ESP is the processor on the receiver.

**Comment by pkendall64** [comment] 2021-07-05 21:10
Please, if you have questions about this issue, ask on discord. The issue tracker is not a forum!

**Comment by m4journey** [comment] 2021-07-05 21:31
> Please, if you have questions about this issue, ask on discord. The issue tracker is not a forum!

may i have a link to discord pls?

**Comment by jklong03** [comment] 2021-07-05 21:39
https://discord.gg/XTTHut3sgf

**Comment by m4journey** [comment] 2021-07-05 21:42
> This is not a bug in the firmware.
> 
> This problem is well known that some FCs cause the receiver TX line to go low at power on which forces the ESP into bootloader mode, hence the solid LED.
> 
> There are a couple of potential fixes/workarounds.
> 
> * Try another UART this behaviour seems to be present on some UARTs on some FCs
> * You can try is to add a small value (300ohm-1kohm) pull up resistor (to 3.3V) to the receiver TX line.

Do you know why it's happening to ep1 and not others like xm+, crsf nanos etc? ARe the using other processors?

**Comment by m4journey** [comment] 2021-07-05 21:50
> https://discord.gg/XTTHut3sgf

Thank you. Verify email is not sending to me for some reason. Having no luck again lol

**Comment by m4journey** [comment] 2021-07-07 15:14
My issue fixed..... I didn't know the Vista was occupying the uart2 (nR2) .... moved to uart 6 and all well.

**Comment by howels** [comment] 2021-07-25 18:51
To clarify for others with this problem - I fixed  this by soldering a 1K resistor between 3v3 on the FC and RX on the EP2 (TX pin on the FC).

**Comment by pitts-mo** [comment] 2021-10-17 22:44
BetaFPV Nano 2.4GHz RX  on GEP-F411-35A AIO default serial rx port 2 also experiences this issue.

My current solution for BetaFPV Nano 2.4GHz RX w/ GEP-F411-35A AIO:
Put ESP based ELRS RX on port 1 and move VTX to soft serial.

Good luck,
-p

more detail:
This GEP-F411-35A AIO came with a new GEPRC SMART 35 Analog.

my findings:
-When the TX pad from the receiver is connected to R2 (default serial rx pads) the blue LED from the receiver just stays on solid even when I had attempted either a 560 ohm or a 330 ohm between 3.3v to R2.

-VTX telemetry for the included VTX will not work on port 2 either.

-I verified a TBS CRSF RX does works fine on port 2.

-One of the manuals I found for this AIO also insists a GPS unit must only be connected to port 1. So I have come to suspect something about the inverters utilized for the "RT2" SBUS pad on this controller may further compound the known issues with ESP based ELRS receivers.

**Comment by mituritsyn** [comment] 2021-12-20 19:04
this issue is silent elrs killer. In local ELRS chat we get huge messages ammount from users with this problem. for most of them, even the usual soldering of the receiver seems to be a difficult task, no one wants to solder additional resistors - it's easier for them to say that elrs is a raw product and go for crossfire.

**Comment by maybenikhil** [comment] 2021-12-21 19:55
Now in the docs: https://www.expresslrs.org/2.0/quick-start/troubleshooting/#i-think-my-rx-and-tx-are-bound-as-the-led-on-the-receiver-is-solid-but-i-dont-have-stick-inputs-or-rssi-on-radio

**Closed by maybenikhil** 2021-12-21 19:55 UTC
Labels: bug

**Comment by mituritsyn** [comment] 2021-12-21 23:09
> Now in the docs: https://www.expresslrs.org/2.0/quick-start/troubleshooting/#i-think-my-rx-and-tx-are-bound-as-the-led-on-the-receiver-is-solid-but-i-dont-have-stick-inputs-or-rssi-on-radio

this shouldn't be in the docs.... it should be on main screen and looks like: if you have f411 or iflight board you definetly shouldn't stick with elrs and stay on crossfire or anything else.... 
Don't get me wrong, I really love this project, but you underestimate this issue...

**Comment by brandonrc** [comment] 2021-12-22 04:01
> this issue is silent elrs killer. In local ELRS chat we get a lot of messages from users with this problem. for most of them, even the usual soldering of the receiver seems to be a difficult task, no one wants to solder additional resistors - it's easier for them to say that elrs is a raw product and go for crossfire.

Silent elrs killer? Then users should use STM based RX's if they are in a unique situation to where they cannot avoid the sbus pad. All my tiny whoop boards have a uart 1 and uart2. I can move the ELRS to the non sbus uart and move the smart audio to the free tx. 

That is a valid solution that should work with these boards. There is no issue just an unfortunate inconvenience I will admit.

**Comment by brandonrc** [comment] 2021-12-22 04:04
> Now in the docs: https://www.expresslrs.org/2.0/quick-start/troubleshooting/#i-think-my-rx-and-tx-are-bound-as-the-led-on-the-receiver-is-solid-but-i-dont-have-stick-inputs-or-rssi-on-radio

Maybe I can make a video showing a tiny whoop with only two uarts. I will move the smart audio to the tx paired with the sbus nonsense and free up a uart that has no issues with ELRS. I do it all the time with my tiny whoops.

**Comment by palia95** [comment] 2022-07-01 17:03
Hi, is there any new RX on the market which works with the AIO FC (GEP-12A-F4) reported in the main thread without any additional pull-up resistor? Cause mine PP RX seems bricked and I have to find an alternative. Thank you

**Comment by mituritsyn** [comment] 2022-07-01 19:36
> Hi, is there any new RX on the market which works with the AIO FC (GEP-12A-F4) reported in the main thread without any additional pull-up resistor? Cause mine PP RX seems bricked and I have to find an alternative. Thank you

No, and developers are still not paying enough attention to the problem. the capacitor problem and frequency drift are well known and discussed so manufacturers have started fixing designs, what's stopping elrs team from doing the same with this problem - all receivers would have had a 3.3V line pull-up long ago

**Comment by palia95** [comment] 2022-07-01 21:27
> > Hi, is there any new RX on the market which works with the AIO FC (GEP-12A-F4) reported in the main thread without any additional pull-up resistor? Cause mine PP RX seems bricked and I have to find an alternative. Thank you
> 
> No, and developers are still not paying enough attention to the problem. the capacitor problem and frequency drift are well known and discussed so manufacturers have started fixing designs, what's stopping elrs team from doing the same with this problem - all receivers would have had a 3.3V line pull-up long ago

Ok, sad to know. Well, I think I will have to ditch ELRS on my Tiny Whoop since I've not been able to make any EP1/2 model work with this FC. I hope to recover the PP RX with the STLink

**Comment by commanderguy3001** [comment] 2022-07-01 21:45
> > Hi, is there any new RX on the market which works with the AIO FC (GEP-12A-F4) reported in the main thread without any additional pull-up resistor? Cause mine PP RX seems bricked and I have to find an alternative. Thank you
> 
> No, and developers are still not paying enough attention to the problem. the capacitor problem and frequency drift are well known and discussed so manufacturers have started fixing designs, what's stopping elrs team from doing the same with this problem - all receivers would have had a 3.3V line pull-up long ago

because the pull-downs on flight computers count as a feature, so it is not an error made by any specific elrs gear producer (unlike the capacitor/oscillator stuff),which means that their designs aren't "wrong" per se, as you also don't need the pull up on any normal uart

**Comment by ptran6507** [comment] 2022-09-20 15:53
GEPRC_F411_AIO, can we put ELRS on soft serial T11 R11, thus free T1 for VTX connection, since T2 is not working ( Device Ready: No ) ? This board has only 2 uart. Thanks.

**Comment by bhelm** [comment] 2023-06-08 18:43
I just want to add one reason why this error (led solid on) can occur: when the dji air unit's sbus is also connected to the R2 on the FC. For me, the elrs receiver worked when i powered the drone via usb but did not work when powered by battery. After removing the sbus cable from the air unit and the GEP-F411-35A AIO FC, the BetaFPV elrs nano receiver also started to work when powered by battery on uart 2. The sbus cable transports the controller signal when using an dji remote, which is not used when using elrs exclusively.

Turns out the problem here was completely unrelated and i was just routed the wrong way by the GEPRC FAQ.
