### ISSUE TITLE
Frsky R9M & R9MM, low LQ barely controllable

### ISSUE THREAD

**Issue by mattcattell** [ExpressLRS/ExpressLRS#1023] opened 2021-10-24 14:44 UTC
## Current Behavior

The radio link fails giving no telemetry with an LQ of < 10%, the control link doesn’t completely stop working but gives the impression of very high latency due to very few error free packets making it thru. 
Cycling the power to the model makes no difference, only cycling power to the transmitter corrects the problem.

## Steps to Reproduce
??
## Details

I had this failure on 3 out of 15 flights today 24/10/21, flying with a friend using crossfire seems to provoke the problem.

Extremely difficult to control model & not trusting the expresslrs over any distance.

stock v1.2.0 build

## Your Environment

- TX hardware: Frsky R9M v1
 - Power output: 100mW & 250mW
- RX hardware: Frsky R9MM
- Handset model: Radiomaster TX16S
- OpenTX version (including nightly number) 2.3.14-otx
- ExpressLRS version (TX & RX MUST MATCH): v1.2.0
- Packet Rate: 200Hz
- Telemetry Ratio: 1:16
- user_defines:
REGULATORY_DOMAIN_EU_868
	FEATURE_OPENTX_SYNC
	HYBRID_SWITCHES_8
	ENABLE_TELEMETRY
	TLM_REPORT_INTERVAL_MS – 300LU
	JUST_BEEP_ONCE

**Comment by sk14Github** [comment] 2021-11-02 13:42
Same Problem. loos LQ. i Try to CLI : failsafe_stick_threshold = 10.
maybe it work better.

**Comment by 0crap** [comment] 2021-11-02 15:53
> Unfortunately the DVR on DJI goggles doesn't record the OSD but from memory LQ was bouncing between 0 & 6%.
Perfectly normal for the link to drop at those LQ values.
 
> I'll setup the black box recorder in betaflight to grab some data for when it happens again.
Sounds like a plan!

**Comment by x4FF3** [comment] 2021-11-05 22:04
Hi, 

sry for the delay, here is my video with the problem: https://www.youtube.com/watch?v=6f6MEF7zJM8
the TX module did restart itself in those flights. to regain control i had to powercycle my taranis.

**Comment by mattcattell** [comment] 2021-11-07 21:48
I’ve finally got chance to go for a flying again.

Betaflight blackbox wasn’t much use for capturing the failure, I thought capturing the crossfire statistics would give some useful data but I don’t think ELRS is sending the statistics packet as it’s always returns 0 but I have captured some data in opentx.

This data freezes when the telemetry falls over but on the OSD the LQ (AUX11) is cycling from 0 to 6 - 10% around every second.

![image](https://user-images.githubusercontent.com/26820304/140662986-1f84559d-8136-42a2-ad75-577568f59992.png)
![image](https://user-images.githubusercontent.com/26820304/140663007-e95f9fb2-bb7a-41d9-9903-bc49f2d6af4c.png)

[Roma_f4-2021-11-07.csv](https://github.com/ExpressLRS/ExpressLRS/files/7493152/Roma_f4-2021-11-07.csv)

**Comment by mattcattell** [comment] 2021-11-07 21:55
ELRS seems rock solid, if I'm flying without anyone else flying on 868 Mhz but as soon as a Crossfire transmitter is on it  causes a problem.

One thing i noticed the TQly stay up at 100% with just ELRS on but as soon as a Crossfire transmitter is on, this value will cycle from 100% down to 90%  around every 5 seconds

**Comment by schugabe** [comment] 2021-11-08 13:24
The 868MHz band is pretty small so it's very likely that the signal quality takes a hit with other transmissions on the same band. That is true for telemetry data + control data.

@mattcattell do you get a FS when a crossfire transmitter is on or does the signal quality go down?

**Comment by mattcattell** [comment] 2021-11-08 13:36
> The 868MHz band is pretty small so it's very likely that the signal quality takes a hit with other transmissions on the same band. That is true for telemetry data + control data.
> 
> @mattcattell do you get a FS when a crossfire transmitter is on or does the signal quality go down?

@schugabe, Yes this triggers a FS in some situations but from this point forward telemetry is permanently lost and the model will be difficult to control due it only receiving an updated command every 0.2/0.3 seconds. This can only regained by cycling the power on my transmitter.

**Comment by mattcattell** [comment] 2021-11-14 21:14
I flew 6 batteries today with V2.0 RC2 and every flight had the problem above, some batteries I landed & restarted the transmitter and it happened again shortly afterwards. A few things to note, the controllability has improved when ELRS drops into this mode but this build seems more susceptible to it failing and also occurred without a crossfire transmitter powered. 

The improved controllability in this failure mode is due to a slightly faster update rate, probably something like 0.1S, presumably due to the variable sync pulse frequency?

I also recorded the following video of the OSD LQ (AUX11) when ELRS drops into this mode, these LQ values are identical to all the failures I've had, the distance from home doesn't change these values.
https://www.youtube.com/watch?v=RzI2YiX7FRc&ab_channel=MatthewCattell

All these flights where short range, 50/60 meters maximum.

**Comment by x4FF3** [comment] 2021-11-15 12:05
> I also recorded the following video of the OSD LQ (AUX11) when ELRS drops into this mode, these LQ values are identical to all the failures I've had, the distance from home doesn't change these values. https://www.youtube.com/watch?v=RzI2YiX7FRc&ab_channel=MatthewCattell

your LQ shows the same behaviour as mine on my talon.

**Comment by error414** [comment] 2021-11-29 22:10
Something similar happened to me last week approx. three times, on the table. 

TBS Mambo + R9M ELRS 2.0.0-RC3

It works ok, but sometimes transmitter lose telemetry and refresh rate drops down to 1-2Hz, I checked it in receiver tab in inav configurator. It confirms what I see on plane, low refresh rate. CPU load was 14%. If it happens lua ELRS script can't load settings from R9M module, I see only "??????". 

Only way how to "recover" it to normal is turn off/on transmitter.  

I would like to help to debug it, but I'm not familiar with platformio + stm32, I use clion + cmake. Would be nice to create simple manual how to start debugging over SWD from platformio.

**Comment by error414** [comment] 2021-12-02 22:29
I set my plane on table and then without any reason again lose telemetry.

**Comment by schugabe** [comment] 2021-12-03 07:53
> I set my plane on table and then without any reason again lose telemetry.
> 
> R9M FW: ELRS compiled from 2.0.x-maintenance 10mW 1/8 telemetry I use Yappu telemetry lua script.
> 
> R9mini receiver: ELRS 2.0.0-RC2
> 
> DVR: https://www.youtube.com/watch?v=sp4njBPYISo video with transmitter at the same time as DVR was recorded: https://www.youtube.com/watch?v=syabkmpXMOY


Do you have the 2018 or 2019 version of the r9m module? Did you use an older version of elrs before that did not have that issue?

**Comment by error414** [comment] 2021-12-03 08:02
I have 2018 + resistor mod. 

Over summer I used 1.x.x version without any problem. I will test it today whether 1.x.x is still ok.

**Comment by schugabe** [comment] 2021-12-03 08:10
> I have 2018 + resistor mod.
> 
> Over summer I used 1.x.x version without any problem. I will test it today whether 1.x.x is still ok.

I had another report of a 2018 module 1.1 working and 1.2 not working. Can you try both versions and report back if this is also true in your case?

**Comment by error414** [comment] 2021-12-03 08:11
Do you mean 2.x.x? Not " 1.2 n"

**Comment by schugabe** [comment] 2021-12-03 08:12
The other guy reported that the issues did start with version 1.2 but version 1.1 was working fine

**Comment by error414** [comment] 2021-12-03 08:14
Ok, will try it

**Comment by YeOldePirate** [comment] 2021-12-03 08:17
try 2.0.x-maintenance, afaik barry's fix did get merged into it

**Comment by error414** [comment] 2021-12-03 09:50
It's difficult to reproduce, because failing is randomly. I did a few test.

1.1 -I couldn't get a failing
1.2 - failing
2.0.x-maintenance - easy to get fail

**Comment by mattcattell** [comment] 2021-12-03 09:59
I'd agree with your findings v1.1 was definitely harder to fail and the latest 2.0rc3 fails easily and is giving me big problems at the moment. 

The only problem with v1.1 is that you lose control of your model and have to rely on the rescue/rth while you cycle the power on your transmitter.

**Comment by error414** [comment] 2021-12-05 16:55
is it fixed?

**Comment by mattcattell** [comment] 2021-12-05 19:07
No, still having problems.

I tried turning off telemetry today and it removes all the failure problem but with 2.0 rc3 the range was shocking at 250mW. My frsky xm+ receiver out performed in by a mile !!

So as a work around i think v1.1 with telemetry disabled might work for short term fix until this problem is resolved.

**Comment by schugabe** [comment] 2021-12-05 19:09
what do you guys do to make it fail on the bench?

**Comment by error414** [comment] 2021-12-06 22:27
I don't know what you want to know. I turn on transmitter, turn on plane and just wait to connection failure.

**Comment by schugabe** [comment] 2021-12-06 22:30
> I don't know what you want to know. I turn on transmitter, turn on plane and just wait to connection failure. I bought new antenna, it didn't solve issue.

More details please: how far appart are tx+rx, how long does it take, how often do you have to plug it in until the error comes up

**Comment by error414** [comment] 2021-12-06 22:46
1) **how far appart are tx+rx**: about 50cm, does not matter if I increase distance

2) **how long does it take**: until I restart transmitter, If it lost connection, connection is never recovered. 
Actually it's not full lost connection, Telemetry does not work but if I move stick, ailerons moves, but frame rate is very low 0.5-1hz. I will create video. LQ is about 5 - 10, it's in video I posted. 


3)  **how often ...**: for version 1.2 about two times and wait 5 - 10min.  for 2.x I would say "every time" and the fastest failure was 30s after turn on transmitter. 

I think that R9 has header pins with uart, maybe would be nice to use it for debug information, or add debug information to lua script.

**Comment by error414** [comment] 2021-12-07 21:46
I  spent whole day to try out what can be wrong or how to reproduce the issue. The issue is randomly. I tried another FC, inav 3 and 4, different distance between TX and RX. Sometimes it fails within 30s after TX bootup, sometimes it works 30min withou any issue.

**Comment by schugabe** [comment] 2021-12-09 10:56
> I spent whole day to try out what can be wrong or how to reproduce the issue. The issue is randomly. I tried another FC, inav 3 and 4, different distance between TX and RX. Sometimes it fails within 30s after TX bootup, sometimes it works 30min withou any issue.

I did flash my R9M + R9mm with RC4 

- options for tx: 868 region + OPENTX_SYNC 
- rx: RX LOCK_ON_FIRST_CONNECTION 
- 200 Hz
- 1:64 tlm ratio
- 10mw
- 400k baud rate setting on radio

And did test like 10 power cycles with 1min run time and had it running once for 60min and everything is working without any issues. I'm not saying that your problems are not real but I can't reproduce it and would suspect something wrong with the hardware. Did you try to lower the baud rate in the opentx settings? @error414

**Comment by error414** [comment] 2021-12-09 11:02
I can't change baud rate because there is not option for that. I use TBS Mambo. It uses freeTx, Should be released edgeTX for TBS mambo soon, so then I will try change baud rate. And I will order new ELRS 868 module.

**Comment by urksl** [comment] 2021-12-26 00:57
R9M 2019 flashed to version 2.0.0 here. Issue still happening.

Occurs randomly: sometimes after 10 minutes, sometimes after 2 hours.
Lowering baud rate in edgeTX from 400000 to 115200 does not make the error disappear. Raising baud rate to 921600 does not make it more error prone.

**Comment by urksl** [comment] 2021-12-27 22:27
Updated the R9M RX and TX to version 2.0.1

It just ran for 5 hours without irreversibly losing telemetry.
After 70 minutes a "telemetry lost"-event happened, but this time telemetry recovered and the link did not stay laggy and degraded afterwards.

On version 2.0.0 I would have already rebooted my TX a few times to make everything work again.

**Comment by brandonrc** [comment] 2022-01-07 00:41
So it looks like this issue happens on the r9m 2019 and the r9m v1? 

@urksl @mattcattell

**Comment by sk14Github** [comment] 2022-01-07 06:17
Still problem with R9 System?!! MMm. All others no Problem but R9 failt. Thats not good. I want fly !!!! i hope That will fixt soon. i dont want more Quands damaget. My patience is at the end.

**Comment by error414** [comment] 2022-01-07 08:49
I had to switch to tracer, I don't have time to wait half year to fix. :(((( Maybe some day I will try ELRS again.

**Comment by urksl** [comment] 2022-01-07 10:49
@brandonrc Yes. It affects me on r9m 2019. And @mattcattell ran into it on the v1.

**Comment by sk14Github** [comment] 2022-01-07 13:48
wat is st-link?

**Comment by error414** [comment] 2022-01-07 14:13
> wat is st-link?

device for flashing/debuging STM32 micro controllers. 

urksl:
I asked authors if there is any possibility to set verbose mode or etc, to find out what is happening when R9 started failing.

**Comment by x4FF3** [comment] 2022-01-11 15:29
did someone test another tx+r9rx? as i would order a es900tx for comparison.

**Comment by AlexZaiets** [comment] 2022-01-21 00:50
Same problem with ELRS 2.0.1, Dynamic power (MAX250mw), 200Hz, Telem 1:8, R9M 2019 + R9 MM-OTA, ErskyTX on AR9X board
Here is the video with OSD and Blackbox overlay (rssi, rxSignalReceived,  rcCommand(throttle)) from iNav 
https://youtu.be/eFII93sD-KI

**Comment by schugabe** [comment] 2022-01-21 23:16
Please test with 2.1: this release does contain some fixes that could help with this issue. I still cannot reproduce the issue with my hardware so it's hard to verify if the release changes the situation.

**Comment by edernucci** [comment] 2022-01-24 16:03
> > wat is st-link?
> 
> device for flashing/debuging STM32 micro controllers.
> 
> urksl: I asked authors if there is any possibility to set verbose mode or etc, to find out what is happening when R9 started failing.

Maybe is not possible, since R9M firmware doesn't compile with debug anymore because of lack of space.

**Comment by sk14Github** [comment] 2022-01-24 18:48
I am very happy to test the new firmware 2.1.0. I will then report it to you. Not sure which Hz rate and tlm ratio is best for long range. What do you all mean?
Thanks ERLS Devs!

**Comment by AlexZaiets** [comment] 2022-02-05 14:54
yesterday I tested ELRS v 2.2.0 - in the same place 8 flights with another pilot nearby on a crossfire with 250mw. It looks like everything is fine. I didn't have a problem with low LQ
Thank you, DEVS!

**Comment by sk14Github** [comment] 2022-02-05 18:53
Yes me too. 20flights without problems. Longrange are comming (to much Snow at the moment). The Dynamic Power; regulates relatively late, around 105-110 db at 50 hz, only then does it go higher to 25mW, I think that should happen earlier, 10% or 20% db before. But first i have to test the Long range.
Thanks DEVS!!!

**Closed** 2022-06-25 03:18 UTC
Labels: closing
