### ISSUE TITLE
GPS telemetry

### ISSUE THREAD

**Issue by BatuP** [ExpressLRS/ExpressLRS#321] opened 2021-01-18 21:11 UTC
Are there any plans to add GPS telemetry to ExpressLRS? Additionally, what are some good resources to look at to start understanding the code base? I am very interested in learning how ExpressLRS works and how to potentially contribute to the project.

**Comment by dyon-b** [comment] 2021-01-18 21:17
For the telemetry part you should check out #204, It’s just waiting to be merged at this point.

**Comment by jejakmedia** [comment] 2021-01-22 12:40
i hope gps telemetry can read on Telemetry Viewer app in android

**Comment by nangel0** [comment] 2021-04-17 16:08
Advanced telemetry has been merged.
Can we close this @BatuP

**Comment by ballistRC** [comment] 2021-04-25 20:18
I was checking telemetry just now and while I noted GPS data, there wasn't any heading information so I dont think magnatometer  data is being forwarded.  This was using BF4.2.8 and the heading was changing when I rotated the Mag.

**Comment by schugabe** [comment] 2021-04-28 18:05
> I was checking telemetry just now and while I noted GPS data, there wasn't any heading information so I dont think magnatometer data is being forwarded. This was using BF4.2.8 and the heading was changing when I rotated the Mag.

The telemetry sensors are transmitted as received by the FC and betaflight mentions GPS heading in a comment. I think that the mag is not used for this field.

**Comment by CapnBry** [comment] 2021-04-29 13:51
Advanced Telemetry supports `CRSF_FRAMETYPE_GPS` which includes lat, long, ground speed, ground course, altitude, and num sats. I can confirm this is working in iNav (and should also work with betaflight since the code is the same) and displaying on opentx.

**Closed by CapnBry** 2021-04-29 13:51 UTC
