### ISSUE TITLE
multiple issues with the Lua script on TX16s

### ISSUE THREAD

**Issue by cbf123** [ExpressLRS/ExpressLRS#2213] opened 2023-05-09 20:30 UTC
## Current Behavior

I'm seeing a few issues with the Lua Script on my TX16s (latest version of the script and of EdgeTX):

1. When starting up the Lua script when connected to a receiver, it can sometimes take a very long time (over a minute) to complete loading the script.  Sometimes it just hangs and never completes.
2. Sometimes the "Other Devices" folder does not show up even though the TX is connected to a bound RX and telemetry is being recieved.  (There is a "C" in the upper right of the Lua script.)
3. When it shows up, the "Other Devices" folder is not visible on the main screen (it's below the ELRS version number) and so it's not at all obvious that it even exists, or that the "----EXIT---" option exists.
4. My receiver is connected to a flight controller running ArduPlane, and sometimes (but not always) under the "Other Devices" folder I get an  "ArduPlane V4.3.5" option.  If I select it, the Lua script throws an error:  https://photos.app.goo.gl/RKysypntYVb8qPu87

## Steps to Reproduce
Turn on TX and RX, wait for the solid light on the RX indicating a bound connection, start the Lua Script.

## Suggested fix ##
It might make sense to put the ELRS version up in the top bar with the TX hardware info?  That way there'd be room on the front page for the "Other Devices" folder at least.

## Your Environment

- TX hardware: TX16s, Happymodel EX24TX Pro
- RX hardware:  Happymodel EP1 Dual TCXO
- EdgeTX version: 2.8.2
- ExpressLRS version (TX & RX MUST MATCH): 3.2.1
- Packet Rate: 250
- Telemetry Ratio: 1:4

The Yaapu telemetry widget is enabled for this model as well.

**Comment by pkendall64** [comment] 2023-05-12 07:51
I believe this is fixed now as we were getting to the point of overflowing the number of lua items we had set and we've increased that number now. See PR #2207.

**Comment by cbf123** [comment] 2023-05-12 15:28
I had mentioned multiple issues....which do you think is fixed?

**Comment by pkendall64** [comment] 2023-05-12 22:32
> I had mentioned multiple issues....which do you think is fixed?

Certainly 2 and 3.
1 is generally caused by a slow connection between the radio and the module i.e. 115k or 400k baud. There are a lot of lua params so they take quite some time to load and when running at the slower baud rates some of the params have to be split across multiple packets. If you have a TX16S then you should be able to run the connection to the module at 3.75 or even 5.25 Megabaud.
For 4, I can't see the image, please drag it into the ticket here rather than providing a link to google as it's saying "Album is empty".

**Closed** 2023-06-14 01:59 UTC
Labels: closing :door:
