### ISSUE TITLE
PWM mode 3.2.1, the device cannot be connected stably, resulting in disconnection

### ISSUE THREAD

**Issue by zimochiu** [ExpressLRS/ExpressLRS#2278] opened 2023-06-29 02:12 UTC
## Current Behavior

PWM mode , the device cannot be connected stably, resulting in disconnection
## Steps to Reproduce

1.

2.

3.

4.

## Possible Solution (Not obligatory)
NOT SURE

## Your Environment

- TX hardware: BETAFPV 2.4G ELRS
- RX hardware: DIY_2400_RX_PWMP 、SX1281 ESP8285
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH): 3.2.1
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by pkendall64** [comment] 2023-06-29 04:28
This is a duplicate of #1988 
The solution is to clear platrformio dependencies and flash. Or use the web-flasher, and check the erase flash option before flashing. https://pkendall64.github.io/elrs-web-flasher/

**Closed by pkendall64** 2023-06-29 04:28 UTC
