### ISSUE TITLE
Excessive High Dynamic Power States from ANT path selection algorithm ?

### ISSUE THREAD

**Issue by silicongarage** [ExpressLRS/ExpressLRS#2852] opened 2024-07-20 03:23 UTC
## Current Behavior
I've been looking through the logs of a recent glider flight and trying to understand the excessive amount of high dynamic power states that occur. 

## Details
From  a simple spreadsheet analysis of the log file:

Flight Log: (63 minutes, 1/2 second rate, LOS)

- Total points:      7560
- `1RSS>2RSS`:         3369 (45%) (expected as most of the flight pattern is circling)
- `1RSS>2RSS && ANT(1)`:  3173 (42%) (wrong antenna selected)
- `ANT(0)`:             250 (3%)
- `TPWR(=250)`:        2613 (35%)

- `TPWR(=250) && (1RSS>2RSS)`:           1062      
- `TPWR(=250) && (1RSS>2RSS) && ANT(1)`:   956 (90%, wrong antenna selected)

My interpretation is that due to the radio path sticking to ANT(1) until fail, the Dynamic Power algorithm will raise TX power to try and compensate for poor ANT(1) alignment relative to TX, resulting in an excessive number of high power states.

## Possible Solution
If both receiver paths pull valid packet interrupt, select path with best RSS

## Environment

- Receiver:  BetaFPV SuperD
- RX ANTs:   both horizontal and orthogonal to each other
- TX ELRS:   Radiomaster Ranger Micro
- TX ANT:    T-type oriented horizontal
- ELRS:      V3.4.3 
- RATE:      100 Full
- TELEM:   1:8
- PWR:       dynamic power both TX & RX, TX max 250mw

**Comment by pkendall64** [comment] 2024-07-20 06:44
This is a duplicate of #2815

**Closed by pkendall64** 2024-07-20 06:44 UTC
