### ISSUE TITLE
Yappu CRSF Ardupilot support

### ISSUE THREAD

**Issue by RMFPV** [ExpressLRS/ExpressLRS#933] opened 2021-09-27 10:27 UTC
Please add it!

More info here
https://discuss.ardupilot.org/t/passthrough-telemetry-over-crsf-crossfire/62668

*Instead of commenting "I want this too", consider leaving a :+1: instead, to reduce spam and clutter*

**Comment by schugabe** [comment] 2021-10-01 07:37
I'm closing this issue because it is a duplicate of #650 
Please follow the other issue for more information on the topic

**Closed by schugabe** 2021-10-01 07:37 UTC
Labels: enhancement
